### ISSUE TITLE
Landing Page for Unauthorized Users

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#11]
for those not in admin, api owner, or developers

**Comment by pauldaustin** [comment]
Leo,

Please provide a more detailed description for enhancements.

1. Which application does it affect (Admin vs Developer key) or which pages of the application
2. Purpose of the enhancement
3. Exact details of the text to appear on a page

**Comment by ll911** [comment]
1, admin app
2, UX enhancement 
3, add a splash screen for first time idirs, says “your profile is initiated, please contact data@gov.bc.ca for more information on API Management Services” then redirect to https://catalogue.data.gov.bc.ca/dataset?tags=API

**Comment by BK01** [comment]
Test successful. Displayed a detailed 403 message for developers and API owners along with instructions and links to gain access.

**Comment by BK01** [comment]
@pauldaustin Please change the back button to an acknowledged button, and have the button close the window.

**Comment by BK01** [comment]
403 message page presented to users with back button and contact info in gwa-t. A modal window is presented to users in gwa-d with a login button.

**Comment by pauldaustin** [comment]
Brian,

gwa-t and gwa-d both seem to be the same for me. You might need to clear your browser cache.
