### ISSUE TITLE
Sorting records in table view

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#13]
in APIs, Plugins, Users, Groups tab
add "descend" & "ascend" for table head, so fields like "Name", "Hosts", "Created at"... can be sorted alphabetically or chronologically

**Comment by pauldaustin** [comment]
Rejected as kong doesn't support this.

Please hold off on enhancements until we get version #1 completed

**Comment by ll911** [comment]
@pauldaustin that's why I didn't included in https://github.com/bcgov/gwa/milestone/1

**Comment by pauldaustin** [comment]
Implement functionality to allow the user to sort the records in a table view. This will be supported for tables where all records can be loaded into memory on the client side. The sort will occur on the client side as Kong doesn't support sorting of results.

The following tables will have sorting enabled.

* Endpoint list
* API list
* API plugins list
* API group list
* Groups list
* Node List

The following kinds of tables won't be sorted as data volumes could be large.

* User list
* Group user list

**Comment by pauldaustin** [comment]
I've implemented the functionality. It'll be available once I deploy 1.1.0
