### ISSUE TITLE
admin ui for api owner

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#14]
API owner can set any API rate limiting even the API owner is someone else.
<img width="803" alt="screen shot 2017-03-31 at 9 34 33 am" src="https://cloud.githubusercontent.com/assets/11949273/24559966/89587974-15f5-11e7-8ea6-e4bf7392d3b5.png">
steps to reproduce
1, create api A and users joe, bob
2, add joe and bob to group gwa_api_owner
3, set api A owner to joe
4, login gwa as bob

**Comment by pauldaustin** [comment]
Leo,

As mentioned that functionality to restrict endpoints to apis that they are api owners is not yet implemented. That's what I'm working on this morning.

**Comment by ll911** [comment]
@pauldaustin duh... bug label removed.

**Comment by ll911** [comment]
confimed
