### ISSUE TITLE
strange page rendering behaviour in safari, not consistent in chrome

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#15]
in api tab, scrolling down the list. safari return blank, chrome return just bottom 2, if click other tab and click api tab again, list restore. 
refresh page also restore the list, see attached screenshot, you can see total sum is correct, but pages show blank or just 2 results in Chrome
<img atl="CHROME" width="1147" alt="screen shot 2017-03-31 at 1 10 09 pm" src="https://cloud.githubusercontent.com/assets/11949273/24568009/fbdf5d5e-1614-11e7-950b-b33b232c5688.png">
<img atl="SAFARI" width="1162" alt="screen shot 2017-03-31 at 1 06 48 pm" src="https://cloud.githubusercontent.com/assets/11949273/24568008/fbdc71a2-1614-11e7-9d7f-83b2c964539a.png">

**Comment by pauldaustin** [comment]
Due to difference in page size between the app and kong.

Fixed and am deploying now

**Comment by pauldaustin** [comment]
Hmm that didn't fix it

**Comment by pauldaustin** [comment]
Fixed. Make sure you do a hard refresh on the page

**Comment by ll911** [comment]
confirmed
