### ISSUE TITLE
Plugin Field Layout and Table properties

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#17]
Add support for adding and editing plugin fields that are table. Table fields have extra nested fields.

Original bug report: https://github.com/bcgov/gwa/issues/16

**Comment by pauldaustin** [comment]
Implement functionality to control the layout and sequence of plugin configuration fields. Kong returns them in a semi-random order. Define the field layout for all existing Kong plugins. Also implement fields for table plugin configuration  fields.

**Comment by pauldaustin** [comment]
Implemented the plugin field layout configuration file format and handling code. Written configuration for all existing plugins if required.
