### ISSUE TITLE
Per Consumer Plugins

### ISSUE THREAD

**Issue by pauldaustin** [bcgov/gwa#18]
Implement functionality to allow administration of per consumer Kong plugins. For example, per consumer rate limiting. For API Owner Endpoints administration the only plugin is consumer rate limiting. For API admin any Kong consumer plugin can be added.

**Comment by pauldaustin** [comment]
As part of this enhancement I'm including the support for plugin user data. For example basic-auth user/password. The full list of plugins are BASIC_AUTH, HMAC_AUTH, JWT, KEY_AUTH, OAUTH2.

**Comment by pauldaustin** [comment]
Then click on the plugin (if exists) or select from the list and click Add Plugin

1. To add a plugin for a user Navigate to the plugins page for the API (e.g. https://gwa-d.apps.gov.bc.ca/int/ui/apis/test/plugins)
2. Click on the Users tab
3. Enter the username and click Add User to open the add plugin page for the user.

User plugins can be viewed from the API - Plugin - Users Tab, Plugins page or Users - Plugins page.

User data (used by plugins) can be accessed on the Data tab for the user.

https://gwa-d.apps.gov.bc.ca/int/ui/users/idir_pxaustin/data

**Comment by BK01** [comment]
Successful test complete in gwa-d
