### ISSUE TITLE
Developer Key Enhancements

### ISSUE THREAD

**Issue by pauldaustin** [bcgov/gwa#19]
Implement the following enhancements to the Developer Key application.

* Provide a version of the developer API key page without a header/footer to support third party applications that may wish to embed it.
* Enable developers to have multiple API keys      
* Apply updated Terms and Conditions text when provided by DataBC
* Support modal window connection between GWA and the existing API console viewer in BCDC.
* Json output for Developer API key app

Changes to the BCDC will be done outside this contract. The contractor will work with the BCDC developer to provide any information required to support the link to the GWA.

**Comment by pauldaustin** [comment]
All pages will accept a contentOnly=true parameter to hide the header and footer menus.

**Comment by pauldaustin** [comment]
The header and footer can be hidden using the query string parameter contentOnly=true.

API Keys and Applications are shown as tables. The API Key table has a delete button to remove specific keys. Multiple keys can be created.

The authorize app section has a select list of all the API keys for the user to select which key to authorize.

I have added a (?) help link to the page pointing to https://github.com/bcgov/gwa/wiki/Developer-Guide

At the moment the API Key Terms of Use points to http://www2.gov.bc.ca/gov/content/home/disclaimer. Can you provide the URL to the page that you will put the terms and conditions on?

The following example shows how to use message passing to get the API key for a user in a bootsrap modal. NOTE: It's important to set the iframe src after the modal has been made visible otherwise it won't work.

The URL is /ui/apiKeys?appName=Test&appSendMessage=true&contentOnly=true

appName - Name of application
appSendMessage=true - Use message passing
contentOnly=true - hide header and footer.

```html
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://unpkg.com/jquery@3.2.1" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>

  <button type="button" class="btn btn-primary btn-lg" onClick="getApiKey()">
    Get API Key
  </button>

  <div class="modal fade" id="apiKeyModal" tabindex="-1" role="dialog" aria-labelledby="apiKeyModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="apiKeyModalLabel">Modal title</h4>
        </div>
        <div class="modal-body">
          <iframe
            id="apiKeyFrame"
            src="about:blank"
            style="width: 100%; height: 600px; border: 0px"
          >
          </iframe>
        </div>
      </div>
    </div>
  </div>
  </body>
  <script type="text/javascript">
function getApiKey() {
      $('#apiKeyModal').modal('show');
      $('#apiKeyFrame').attr('src', 'https://gwa-d.apps.gov.bc.ca/ui/apiKeys?appName=Test&appSendMessage=true&contentOnly=true');
}

    window.addEventListener('message', function(message) {
      $('#apiKeyModal').modal('hide');
      alert(message.data);
    });
  </script>
</html>
```

I'm not going to include JSON output as that is less secure than message passing as it would require CORS and allow access without the user approving access to the API key.

**Comment by BK01** [comment]
To initiate further UAT in DLV once deployed.

UAT thus far:
> Enable developers to have multiple API keys - OK
> GWA without a header/footer (via parameter) - OK

**Comment by BK01** [comment]
Test repeated with success using new gwa deployment.
