### ISSUE TITLE
Log out screen message

### ISSUE THREAD

**Issue by BK01** [bcgov/gwa#20]
When an API owner (IDIR) attempts to log out of GWA they are presented with a screen containing the following message:

"This site can’t be reached

The web page at https://gwa.apps.gov.bc.ca/int/logout might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE"

**Comment by pauldaustin** [comment]
The old version removed cookies and redirected back to the same page.

The new version redirects to https://logon.gov.bc.ca/clp-cgi/logoff.cgi

FYI that page before accepted a returl. But now that doesn't seem to work.

**Comment by BK01** [comment]
Thank you Paul. I will QA in DLV once available.
