### ISSUE TITLE
Cookieless authentication

### ISSUE THREAD

**Issue by banders** [bcgov/gwa#23]
We aim to integrate the GWA application into the BCDC API Console (which is a custom version of swagger-ui embedded into a CKAN plugin).  

The idea is to have a button within swagger-ui called "Get API Key".  Clicking that button will cause swagger-ui (a client-side app) to communicate with the GWA REST endpoint to fetch an API key. To do that GWA must support CORS.  Leo recently enabled CORS by adding the following header to responses from GWA:

Access-Control-Allow-Origin: *

... but the GWA REST endpoint seems to require a session tracking cookie to be passed with any request to the endpoint.  The requirement for a cookie presents a problem because browsers don't allow CORS from the wildcard (*) domain for requests that take cookies.  Browsers give an error like this:

Cannot load http://gwa-t.apps.gov.bc.ca/rest/apiKeys. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. 

Do we have any option to modify GWA so cookies don't need to be passed when calling the REST endpoint?  Access tokens in HTTP headers or query string parameters should be fine...

**Comment by ll911** [comment]
@pauldaustin any suggestion?

**Comment by ll911** [comment]
fix by using REGEX in CORS

**Comment by pauldaustin** [comment]
Leo

Please don't mess with the contract of the API outside of the application code. You have just opened a security hole in the application that allows apps to access the users api key without their permission.

At this point that URL is not designed to be used by other applications to access the API key.

The current correct way is that the application redirects the user to the API key page with the callback URL th at will be passed the API key when the user clicks th e approve access button. See the email I sent you. 

If an alternate approach is required that will need to be implemented in the next release.

Until then remove the extra headers you added to allow cors.

**Comment by pauldaustin** [comment]
I've linked this to the original enhancement request for Developer key enhancements
