### ISSUE TITLE
UI header/footer

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#25]
Can you restore the header/footer look/feel to comply with https://github.com/bcgov/Gov-2.0-Bootstrap-Skeleton 
header/footer look/feel (font/margin/indentation/size) should match with http://engage.gov.bc.ca/data/ (no search box/hamburger menu is fine)

**Comment by BK01** [comment]
Header and footer look/feel match and links are functional. @ll911 look ok to you?
