### ISSUE TITLE
developer key app width

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#26]
need GWA not to require horizontal scrolling in windows of ~450px width. width required for modal window

**Comment by pauldaustin** [comment]
Fixed and deployed to delivery.

FYI the absolute minimum width for this page is 420px. Any padding required in the iframe for the dialog must be added on top of that 420px width.

**Comment by ll911** [comment]
@BK01 @pauldaustin maybe we should add additional arg for each card, e.g ```?contentOnly=true&keyonly=y``` or ```?contentOnly=true&apilist=y```, so the get apikey button can get one card instead all in modal window

**Comment by pauldaustin** [comment]
Leo,

I'm going to keep it simple.

If the appName=... parameter is specified then the page is in the authorize application mode and only the first panel is shown.

Otherwise it is in regular mode and the list of api keys and authorized endpoints (apps) is shown.

**Comment by BK01** [comment]
That should be fine as the console's get key request specifies the parameter (appName=API%20Console). Consequently no code changes on the API console (BCDC) side are required.

**Comment by BK01** [comment]
Modal window UAT completed successfully. Horizontal and vertical scroll bars are no longer present in gwa-d.
