### ISSUE TITLE
Modal window - GWA element width

### ISSUE THREAD

**Issue by BK01** [bcgov/gwa#28]
When clicking the 'Get API key' button in the gated-geocoder API console (in cad.data.gov.bc.ca) a modal window appears. Within the modal window is a GWA page. Currently there is botha horizontal and vertical scroll bar.

1. Is it possible to adjust the width of the GWA elements to remove the horizontal scroll bar?
2. Is it possible to only show the 'Authorize application API Console' element to remove the need for the vertical scroll bar? Or must the 'Developer API Key' and 'Applications' elements also be shown?

**Comment by pauldaustin** [comment]
See #26

**Comment by BK01** [comment]
Duplicate.
