### ISSUE TITLE
js package minify

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#3]
js package minify

**Comment by pauldaustin** [comment]
I'm getting closer to a solution. But thew restrictions and slowness of the siteminder protected site is a large hinderance.

**Comment by pauldaustin** [comment]
Leo fixed the apache2 to jetty proxy so that it wasn't dropping connections.

Implemented a custom webpack configuration to exclude angular, rjxs and ngx-datatable from the bundle. Those will be loaded using systemjs fro unpkg.com.
