### ISSUE TITLE
status page scrolling bug -- see attached screenshot

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#32]
Step to reproduce,
1, click on status tag
2, click on any other tab
3, click on status tab again
4, the more other tab clicked, the longer status tab gets when click again.
![gwa-1 2 0-bug](https://user-images.githubusercontent.com/11949273/29990796-05f657ba-8f33-11e7-94cd-451b1c0a2808.png)

**Comment by pauldaustin** [comment]
Upgraded datatable library didn't like fields called value. So I've changed it to text.

Not deployed fix to the Ministry yet.

**Comment by BK01** [comment]
Fixed in gwa-d. Tested with chrome and firefox.

**Comment by BK01** [comment]
Also appears ok in gwa-t. Tested with chrome and firefox

**Comment by pauldaustin** [comment]
Brian,

There is no point testing gwa-t as it’s the current prod version not the new version.
