### ISSUE TITLE
user tab scrolling trigger kong error

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#36]
Kong version = 0.11.x
GWA version 1.2.0

when consumers > 100 
https://gwa.apps.gov.bc.ca/int/ui/users, when keep scrolling on the user page, will trigger the kong error. 
but when access $KONG_ADMIN_ENDPOINT/consumers no problem.

<img width="292" alt="screen shot 2017-10-27 at 1 28 21 pm" src="https://user-images.githubusercontent.com/11949273/32123965-1057c2a2-bb1b-11e7-8625-926eb360ac7f.png">

**Comment by pauldaustin** [comment]
What’s the error in the log file?

**Comment by ll911** [comment]
@pauldaustin there is no gwa error in logs, but lots of calls listed as following when scrolling. then those calls gets dropped when reach kong admin endpoint rate limit, will return 503 from admin endpoint. 
```
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=0&limit=100 HTTP/1.1" 200 4982 
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=1&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=2&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=4&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=6&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=8&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=1&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=9&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:58 +0000] "GET /int/rest/users?offset=10&limit=100 HTTP/1.1" 200 62
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=9&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=11&limit=100 HTTP/1.1" 200 62
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=10&limit=100 HTTP/1.1" 200 62
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=12&limit=100 HTTP/1.1" 200 62
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=9&limit=100 HTTP/1.1" 200 4982
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=11&limit=100 HTTP/1.1" 200 62
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=13&limit=100 HTTP/1.1" 200 62
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=12&limit=100 HTTP/1.1" 200 62
  | 172.51.20.1 - - [27/Oct/2017:20:26:59 +0000] "GET /int/rest/users?offset=12&limit=100 HTTP/1.1" 200 62

```

**Comment by pauldaustin** [comment]
If you look in the Javascript console in your browser are the errors? And then look at the network requests in the browser and see what the response was where there was an error from the server.

I don’t have access to production so more info == easier to find the issue.

**Comment by ll911** [comment]
@pauldaustin 
here is the log when scrolling on the user tab, other tabs are fine for now, assume because they were under 100.

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'count' of null
TypeError: Cannot read property 'count' of null
    at main.d8b5cff937b84cae52e1.bundle.js:1
    at t.invoke (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at Object.onInvoke (vendor.2c9fb59dbb1a764fa673.bundle.js:1)
    at t.invoke (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at r.run (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at polyfills.d544f1e4518e36c9491e.bundle.js:1
    at t.invokeTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at Object.onInvokeTask (vendor.2c9fb59dbb1a764fa673.bundle.js:1)
    at t.invokeTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at r.runTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at main.d8b5cff937b84cae52e1.bundle.js:1
    at t.invoke (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at Object.onInvoke (vendor.2c9fb59dbb1a764fa673.bundle.js:1)
    at t.invoke (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at r.run (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at polyfills.d544f1e4518e36c9491e.bundle.js:1
    at t.invokeTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at Object.onInvokeTask (vendor.2c9fb59dbb1a764fa673.bundle.js:1)
    at t.invokeTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at r.runTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at c (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at polyfills.d544f1e4518e36c9491e.bundle.js:1
    at t.invokeTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at Object.onInvokeTask (vendor.2c9fb59dbb1a764fa673.bundle.js:1)
    at t.invokeTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at r.runTask (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at o (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at e.invokeTask [as invoke] (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at h (polyfills.d544f1e4518e36c9491e.bundle.js:1)
    at XMLHttpRequest.v (polyfills.d544f1e4518e36c9491e.bundle.js:1)
```
if more info required, maybe schedule a web session?

**Comment by pauldaustin** [comment]
The data table library I was using triggered multiple requests for a scroll. I have changed my code to only call the web service if the offset on the paging changed. There was also a null pointer check I added if no result can back from the server.

You may also want to tweak your rate limiting settings.

FYI I'm getting an error trying to deploy to the delivery tomcat. See the last Jenkins build

**Comment by ll911** [comment]
@pauldaustin add steps remove last deployable from JVMs, should be ok now.

**Comment by pauldaustin** [comment]
Build works but https://gwa-d.apps.gov.bc.ca is blank

**Comment by ll911** [comment]
it's in tomcat, did you define the context path? by default, it will be deployed as /$deployed_file_name

**Comment by pauldaustin** [comment]
It's in the war https://cis.data.gov.bc.ca/job/APIM/job/gwa/ws/target/gwa-1.2.1-SNAPSHOT/META-INF/context.xml/*view*/

**Comment by ll911** [comment]
the UI loads for me, but error logs says cannot connect to kong admin endpoint, looks like it using the default kong admin instead of using the one from config file 
https://applogs-d.apps.gov.bc.ca/int/gwacat/catalina.out

**Comment by ll911** [comment]
looks good so far. no kong error show up in gwa-d

**Comment by pauldaustin** [comment]
Leo,

This script would create 100 users to trigger the issue.

for i in `seq 1 100`; do curl -i -X POST   --url http://localhost:8001/consumers/   --data "username=zzzz$i"; done

**Comment by ll911** [comment]
@pauldaustin thx, i did sth similar 
```for i in $(seq 1 100); do http POST $KONG_ADMIN_API/consumers username=zzxxz$i; done```
it wont give kong error now, but will produce a blank screen

<img width="1197" alt="screen shot 2017-10-27 at 5 02 02 pm" src="https://user-images.githubusercontent.com/11949273/32129093-97b89f6a-bb38-11e7-96ff-f87b38155e58.png">

**Comment by BK01** [comment]
@ll911 @pauldaustin Successful UAT with 1.2.1 in PROD.
