### ISSUE TITLE
UI: Add user to group, then view

### ISSUE THREAD

**Issue by BK01** [bcgov/gwa#37]
In GWA I am an owner of the geocoder endpoint and can normally add and remove members to both groups.

Currently I am unable to see the list of users within either group (geocoder_user or geocoder_gh_user).

On Oct 27th at 10:23am I was able to add a GitHub user to the 'geocoder_gh_user' group (verified by middleware team), but was unable to see the new user name listed in the [group member page](https://gwa.apps.gov.bc.ca/int/ui/endpoints/geocoder/groups/geocoder_gh_user) after I added it.

**Comment by pauldaustin** [comment]
Do you get any errors in the Javascript console?

Which browser etc?

**Comment by BK01** [comment]
Browser: Chrome version 61.0.3

**Comment by pauldaustin** [comment]
Brian,

I'm holding off on this to see if the 1.2.1. paging issue that I fixed solves this. So can you test when 1.2.1 goes to prod?

**Comment by BK01** [comment]
Will do. Thank you Paul.

**Comment by BK01** [comment]
@pauldaustin @ll911 Fix verified in PROD with GWA version 1.2.1
