### ISSUE TITLE
API key rotation

### ISSUE THREAD

**Issue by BK01** [bcgov/gwa#44]
For github users with API keys perform the following cleanup based on the configurable api key expiry days.

- Create a new key for a user if their newest key is older than 90% of the api key expiry days.
- Delete api keys that are older than the api key expiry days
- Show the key age in the developer key list

**Comment by pauldaustin** [comment]
- Function to add basic auth for github user on dev key page, also to change
- New API secured using user's basic auth to generate a new key. So the apps can automate key gen
- Background process in WAR that will daily delete keys older than n days

**Comment by pauldaustin** [comment]
Changed the authentication filter to pick up the kong authentication if provided. In that case the user isn't redirected to the github login page. This will require a second mapping for the developer keys app in kong (e.g. gwa-keys.apis.gov.bc.ca). That would be secured with HTTP basic auth. So the developer can use the gwa.apps.gov.bc.ca using their github login or the gwa-keys.apis.gov.bc.ca using a http basic auth attached to their github login.

**Comment by pauldaustin** [comment]
Added the process that runs at 5:00 in the morning to delete any API keys that are older than the configured expiry (default 90 days). It will only delete keys owned by usernames starting with github_.

**Comment by pauldaustin** [comment]
Added an expiryDays to the API key list. The key and expiry days will be shown in red if the key expires in <= 7 days

**Comment by BK01** [comment]
Please proceed to set developer API keys to expire in value defined in gwa.properties, and create a new key in 90% of the lifetime set in gwa.properties. Set at 90 days for now.
