### ISSUE TITLE
gwa admin function for import and export kong configuration data

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#8]
gwa admin function for import and export kong configuration data from backend db.

**Comment by pauldaustin** [comment]
Not included in the scope of work for version 1.

**Comment by pauldaustin** [comment]
NOTE: For basic-auth the passwords are encrypted. This means it is not possible to backup and restore them correctly.

**Comment by pauldaustin** [comment]
Now deployed to delivery.

https://gwa-d.apps.gov.bc.ca/int/ui/importExport

Click the Export button to save the current configuration.

Select the file and click Import to import the saved file. All records should be shown as Matched.

The list shows what was imported with links to the item. The (?) shows details of that record that was imported and any errors.

Change some config in the UI, delete some items and import again to check the imports work.

**Comment by ll911** [comment]
@pauldaustin for basic-auth, just need to backup username, for password you can output them as ```<reset password required>```

**Comment by BK01** [comment]
Initial testing in gwa-d look good. More testing to be completed shortly.
